<?php

namespace ContainerVKTaywh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerprofilePageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.WO7jUZw.App\Controller\ProfileController::profilePage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WO7jUZw.App\\Controller\\ProfileController::profilePage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postsRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'postsRepository' => 'App\\Repository\\PostsRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]))->withContext('App\\Controller\\ProfileController::profilePage()', $container);
    }
}
