<?php

namespace ContainerIXOb3Rh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SHFqxJ3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SHFqxJ3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SHFqxJ3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LoginSignUpController::register' => ['privates', '.service_locator.egipcEH.App\\Controller\\LoginSignUpController::register()', 'getLoginSignUpControllerregisterService', true],
            'App\\Controller\\LoginSignUpController::login' => ['privates', '.service_locator.xmsm1s9.App\\Controller\\LoginSignUpController::login()', 'getLoginSignUpControllerloginService', true],
            'App\\Controller\\MainInterfaceController::index' => ['privates', '.service_locator.cv37jhs.App\\Controller\\MainInterfaceController::index()', 'getMainInterfaceControllerindexService', true],
            'App\\Controller\\MainInterfaceController::postAction' => ['privates', '.service_locator.q4lVo8g.App\\Controller\\MainInterfaceController::postAction()', 'getMainInterfaceControllerpostActionService', true],
            'App\\Controller\\MainInterfaceController::deleteAction' => ['privates', '.service_locator.F.mlgcH.App\\Controller\\MainInterfaceController::deleteAction()', 'getMainInterfaceControllerdeleteActionService', true],
            'App\\Controller\\SessionController::onKernelController' => ['privates', '.service_locator.cTVgQ4H.App\\Controller\\SessionController::onKernelController()', 'getSessionControlleronKernelControllerService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LoginSignUpController:register' => ['privates', '.service_locator.egipcEH.App\\Controller\\LoginSignUpController::register()', 'getLoginSignUpControllerregisterService', true],
            'App\\Controller\\LoginSignUpController:login' => ['privates', '.service_locator.xmsm1s9.App\\Controller\\LoginSignUpController::login()', 'getLoginSignUpControllerloginService', true],
            'App\\Controller\\MainInterfaceController:index' => ['privates', '.service_locator.cv37jhs.App\\Controller\\MainInterfaceController::index()', 'getMainInterfaceControllerindexService', true],
            'App\\Controller\\MainInterfaceController:postAction' => ['privates', '.service_locator.q4lVo8g.App\\Controller\\MainInterfaceController::postAction()', 'getMainInterfaceControllerpostActionService', true],
            'App\\Controller\\MainInterfaceController:deleteAction' => ['privates', '.service_locator.F.mlgcH.App\\Controller\\MainInterfaceController::deleteAction()', 'getMainInterfaceControllerdeleteActionService', true],
            'App\\Controller\\SessionController:onKernelController' => ['privates', '.service_locator.cTVgQ4H.App\\Controller\\SessionController::onKernelController()', 'getSessionControlleronKernelControllerService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LoginSignUpController::register' => '?',
            'App\\Controller\\LoginSignUpController::login' => '?',
            'App\\Controller\\MainInterfaceController::index' => '?',
            'App\\Controller\\MainInterfaceController::postAction' => '?',
            'App\\Controller\\MainInterfaceController::deleteAction' => '?',
            'App\\Controller\\SessionController::onKernelController' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LoginSignUpController:register' => '?',
            'App\\Controller\\LoginSignUpController:login' => '?',
            'App\\Controller\\MainInterfaceController:index' => '?',
            'App\\Controller\\MainInterfaceController:postAction' => '?',
            'App\\Controller\\MainInterfaceController:deleteAction' => '?',
            'App\\Controller\\SessionController:onKernelController' => '?',
        ]);
    }
}
