<?php

namespace Container6xEmVex;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainInterfaceControllerpostActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q4lVo8g.App\Controller\MainInterfaceController::postAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q4lVo8g.App\\Controller\\MainInterfaceController::postAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'usersRepository' => 'App\\Repository\\UsersRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\MainInterfaceController::postAction()', $container);
    }
}
