<?php

namespace Container2a5u7JW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainInterfaceControllerdeleteActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L7ftYGK.App\Controller\MainInterfaceController::deleteAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L7ftYGK.App\\Controller\\MainInterfaceController::deleteAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postsRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
            'likesRepository' => ['privates', 'App\\Repository\\LikesRepository', 'getLikesRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'postsRepository' => 'App\\Repository\\PostsRepository',
            'likesRepository' => 'App\\Repository\\LikesRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\MainInterfaceController::deleteAction()', $container);
    }
}
