<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVKTaywh\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVKTaywh/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVKTaywh.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVKTaywh\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerVKTaywh\App_KernelTestDebugContainer([
    'container.build_hash' => 'VKTaywh',
    'container.build_id' => '1e7d2d04',
    'container.build_time' => 1738977855,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVKTaywh');
