<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFE70U4p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFE70U4p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFE70U4p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFE70U4p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFE70U4p\App_KernelDevDebugContainer([
    'container.build_hash' => 'FE70U4p',
    'container.build_id' => '92de7910',
    'container.build_time' => 1738427605,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFE70U4p');
