<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2a5u7JW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2a5u7JW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2a5u7JW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2a5u7JW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2a5u7JW\App_KernelDevDebugContainer([
    'container.build_hash' => '2a5u7JW',
    'container.build_id' => 'f20c9a95',
    'container.build_time' => 1738598092,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2a5u7JW');
