<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCJKBTfI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCJKBTfI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCJKBTfI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCJKBTfI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCJKBTfI\App_KernelDevDebugContainer([
    'container.build_hash' => 'CJKBTfI',
    'container.build_id' => '22ea2580',
    'container.build_time' => 1738963929,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCJKBTfI');
